server:
  port: 8081
  servlet:
    context-path: caos
spring:
  datasource:
    #DEV
    url: jdbc:mysql://localhost:3306/caos
    username: root
    password: root
    class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
debug: false
