spring:
  datasource:
    url: jdbc:mysql://localhost:3306/engenharia?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    open-in-view: true
server:
    port: 8081

