spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hefesto?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    main:
      allow-bean-definition-overriding: true
debug: false
server:
  port: 8082