jwt:
  header: Authorization
  secret: E962E89962792C414F83F7C9CF5556BA
server:
  compression:
    enabled: true
    min-response-size: 1
  servlet:
    context-path: /lm-instala-api
spring:
  main:
    banner-mode: console
  datasource:
    #DEV
    url: jdbc:mysql://35.198.2.136:3306/lmbr_dev_provider?zeroDateTimeBehavior=convertToNull&serverTimezone=America/Sao_Paulo
    username: lm-instala-dev
    password: kA9YQyuq
    class-name: com.mysql.cj.jdbc.Driver
    protocol: tcp
    tomcat:
      initial-size: ${DB_INITIAL_SIZE:15}
      max-active: ${DB_MAX_ACTIVE:50}
      max-idle: ${DB_MAX_IDLE:15}
      min-idle: ${DB_MIN_IDLE:8}
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    table: schema_version
    enabled: false
  jackson:
    default-property-inclusion: always
    date-format: yyyy-MM-dd'T'HH:mm:ss
  jmx:
    default-domain: lm-instala-jobs
  mail:
    host: smtp.mandrillapp.com
    port: 587
    username: Leroy Merlin
    password: 5PlYe3nVFNhquY7_WrA0oQ
    protocol: smtp
    default-encoding: UTF-8
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.mandrillapp.com
  mvc:
    async:
      request-timeout: -1
debug: false
logging:
  level:
    org.springframework: INFO
    com.adeo: INFO
endpoints:
  jmx:
    domain: lm-instala-auth
    unique-names: true
api:
  timezone: ${APP_TIMEZONE:America/Sao_Paulo}
  key: "key"
  url:
    #MODO DEV LOCAL
    #lm-instala: http://localhost:8084/lm-instala-api
    lm-instala: https://lm-instala-core-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-api
    lm-instala-pdp: https://lm-instala-provider-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-provider
    #lm-instala-pdp: http://localhost:8086/lm-instala-provider
    lm-instala-auth: https://lm-instala-auth-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-auth
    lm-instala-satsftn: https://lm-instala-satsftn-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-rating
    lm-instala-param: https://lm-instala-parameters-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-parameters
    lm-instala-i18n: https://lm-instala-translations-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-translations
    lm-instala-schedule: https://lm-instala-schedule-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-schedule
    lm-instala-intermediation: https://lm-instala-intermediation-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-intermediation
    lm-instala-budget: https://lm-instala-budget-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-budget
    lm-instala-jobs: https://lm-instala-jobs-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-jobs
    lm-instala-core-elastic: https://lm-instala-core-elastic-developer.k8s-apps.lh-brlm.tech.adeo.cloud/lm-instala-core-elastic
management:
  security:
    enabled: false
    oauth2:
      client:
        registration:
          ping:
            client-id: ${OIDC_AUTHORIZATION_CODE_CLIENT_ID}
            client-secret: ${OIDC_AUTHORIZATION_CODE_CLIENT_SECRET}
            redirect-uri: ${INSTALA_DIRECT_URL}/lm-instala-auth/oauth2/callback/ping
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE:authorization_code}
            scope: ${SCOPE:openid,profile,email,advprofile}
            front-redirect-uri: ${INSTALA_DIRECT_URL}/ping-auth
            front-redirect-provider-uri: ${INSTALA_DIRECT_PROVIDER_URL:}/ping-auth
            end-session-uri: ${OIDC_ISSUER_URI}/idp/startSLO.ping
        provider:
          ping:
            issuer-uri: ${OIDC_ISSUER_URI}
        debug: false
  health:
    defaults:
      enabled: false
service:
  account:
    firebase:
      file: service-account-key-dev.json
      host: https://lmbr-instala-dev.firebaseio.com
    cloud-storage:
      credential: cloud-storage-dev.json
      project-id: lmbr-instala-dev-brlm
vault:
  auth:
    method: approle
    token: s.Gy9vL3CX81R9pwgvrTR9CuqQ
    roleId: dd7f2338-f603-d359-2e28-0563c2864062
    secretId: 6ab853ab-ecc3-6b0a-6704-40997fbbf994
    approlePath: approle-instala
  endpoint:
    host: vault.leroymerlin.com.br
    port: 443
    scheme: https
    path: v1
    engine: instala
    engine-path-parameters: developer/parameters
instala:
  oidc:
    client-id: 0R988bfdef10cb3588be3c0213e9b08ff0
    client-secret: l(MmMp(VlhpRX?B:,IjQaUVfY1:Dv5Vfvz)hVNA2oT
    retry-delay-seconds: 120
app:
  security:
    token-uri: ${OIDC_TOKEN_URI:https://idpb2e-rec.adeo.com/as/token.oauth2}
    authorization-uri: ${OIDC_AUTHORIZATION_URI:https://idpb2e-rec.adeo.com/as/authorization.oauth2}
    user-info-uri: ${OIDC_USER_INFO_URI:https://idpb2e-rec.adeo.com/idp/userinfo.openid}
    jwks-uri: ${OIDC_JWKS_URI:https://idpb2e-rec.adeo.com/ext/oauth/jwks}
allowedUrls: ${ALLOWED_URLS:*}
provider:
  store: ${STORE_PROVIDER:local}
  products: ${PRODUCTS_PROVIDER:local}
  groups: ${GROUPS_PROVIDER:local}